[build]
  base = "."                        # root directory
  command = "npm install && npm run build"
  publish = "client/dist"           # contains index.html

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
