[build]
  base = "."                      # run in repo root
  command = "npm install && npm run build"
  publish = "client/dist"         # publish folder created after build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
