[build]
  base = "."               # root folder
  command = "npm run build"
  publish = "client/dist"  # folder created by build script

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
